
forque/force_torque_sensor_controller:
  type: force_torque_sensor_controller/ForceTorqueSensorController
  publish_rate: 100

forque/bias_controller:
  type: trigger_controller/TriggerController
  resource_name: /biasTrigger

